spring:    ##配置client端注册到 admin ui平台
  boot:
    admin:
      client:
        url: http://localhost:8080
server:
  port: 8081
  ##开放所有监控权限
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
